name: sporttag
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^11.0.0
  http: ^1.1.0
  logger: ^2.4.0
  parse_server_sdk_flutter: ^10.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdfviewer: ^33.2.13
  web: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/sporttag_config.json
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"